### ISSUE TITLE
Can't install pod-inpect on darwin arm64 (Macbook Air M1)

### ISSUE THREAD

**Issue by scraly** [jpriebe/kubectl-pod-inspect#4]
Hi, on my MacBook Air M1 (darwin - arm64), 
I can't install pod-inpect plugin :(

```
$ kubectl krew install pod-inspect
Updated the local copy of plugin index.
...
Installing plugin: pod-inspect
W0415 10:37:06.623486   72112 install.go:164] failed to install plugin "pod-inspect": plugin "pod-inspect" does not offer installation for this platform
F0415 10:37:06.623628   72112 root.go:79] failed to install some plugins: [pod-inspect]: plugin "pod-inspect" does not offer installation for this platform
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0x14000134001, 0x140003c4000, 0x9c, 0xea)
	/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:1021 +0xac
k8s.io/klog/v2.(*loggingT).output(0x10127a900, 0x14000000003, 0x0, 0x0, 0x14000266a80, 0x100fed2e5, 0x7, 0x4f, 0x1400017de00)
	/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:970 +0x164
k8s.io/klog/v2.(*loggingT).printDepth(0x10127a900, 0x14000000003, 0x0, 0x0, 0x0, 0x0, 0x1, 0x1400026a810, 0x1, 0x1)
	/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:733 +0x120
k8s.io/klog/v2.(*loggingT).print(...)
	/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:715
k8s.io/klog/v2.Fatal(...)
	/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:1489
sigs.k8s.io/krew/cmd/krew/cmd.Execute()
	/home/runner/work/krew/krew/cmd/krew/cmd/root.go:79 +0x224
main.main()
	/home/runner/work/krew/krew/cmd/krew/main.go:25 +0x3c

goroutine 18 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x10127a900)
	/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:1164 +0x70
created by k8s.io/klog/v2.init.0
	/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:418 +0x128
```

**Comment by jpriebe** [comment]
I merged your pull request, rebuilt pod-inspect to version 0.1.9, and submitted to the krew-index.  My version upgrade was merged, so v0.1.9 should be available.  Can you check to see if you can install it on your M1?  Thanks!

**Comment by scraly** [comment]
Sorry I was in conference last week, an intense week :-D.
It's perfect, I just tested :) 
<img width="582" alt="image" src="https://user-images.githubusercontent.com/2543381/165064288-d53c267f-3284-47e8-8955-51c3123f62d9.png">

pod-inspect is now installed on my macbook air M1 and is running.

<img width="725" alt="image" src="https://user-images.githubusercontent.com/2543381/165064371-e26e6861-c894-4d54-8173-1de31b5ff9f6.png">

**Comment by jpriebe** [comment]
Thanks for testing it out, and thank you for the contribution!
